apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-service
  template:
    metadata:
      labels:
        app: otp-service
    spec:
      containers:
        - name: otp-service
          image: otp-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
